### ISSUE TITLE
recover_from_errors causing seg fault

### ISSUE THREAD

**Issue by M-A-Robson** [jlloyd237/pyfranka#1]
Using panda system version 4.2.1 (latest i think) on franka I was getting a segmentation fault trying to run the CRI panda examples.

I've rebuilt after removing calls to _client.recover_from_errors() in the PyFrankaController class and the issue goes away. Not sure what is going on in the c++ call to libfranka or if something has changed there which is causing the fault?

Currently the class only calls recover_from_errors() in the init and close functions.

Thanks for the brilliant library by the way!

**Comment by M-A-Robson** [comment]
It appears that the problem is in the hasErrors function of robot.cpp

i changed:
```
bool Robot::hasErrors() {
//    	checkVelocityControlNotRunning_();
		auto state = vcThreadRunning_ ? robotState_ : robot_.readOnce();
	}
```
to:
```
bool Robot::hasErrors() {
   	        checkVelocityControlNotRunning_();
		return bool(robot_.readOnce().current_errors);
	}
```

**Comment by jlloyd237** [comment]
Yes, you’re right.  Good spot! The method was missing a return statement: return bool(state.current_errors);
